# Generated by Django 4.2.1 on 2023-06-01 21:24

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=isbn_field.fields.ISBNField(
                max_length=28,
                validators=[isbn_field.validators.ISBNValidator],
                verbose_name="ISBN",
            ),
        ),
    ]
