apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
data:
  SECRET_KEY: {{ .Values.bookstoreConfigmap.SECRET_KEY | quote }}
  DEBUG: {{ .Values.bookstoreConfigmap.DEBUG | quote }}
  USE_S3_BUCKET: {{ .Values.bookstoreConfigmap.USE_S3_BUCKET | quote }}