apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
data:
  DB_TYPE: {{ .Values.bookstoreSecret.DB_TYPE | quote }}
  DB_USER: {{ .Values.bookstoreSecret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.bookstoreSecret.DB_PASSWORD | quote }}
  DB_NAME: {{ .Values.bookstoreSecret.DB_NAME | quote }}
  DB_HOST: {{ .Values.bookstoreSecret.DB_HOST | quote }}
  DB_PORT: {{ .Values.bookstoreSecret.DB_PORT | quote }}