apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secret
type: Opaque
data:
  DB_TYPE: "cG9zdGdyZXM="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "YW1hbGl0ZWNo"
  DB_NAME: "Ym9va3N0b3Jl"
  DB_HOST: "YWVnaXMtbGl2ZS5jazBkd3pmYzE2eGYuZXUtd2VzdC0xLnJkcy5hbWF6b25hd3MuY29t"
  DB_PORT: "NTQzMg=="